apiVersion: v1
kind: ServiceAccount
metadata:
  name: assurance-hub-api
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: assurance-hub-collector
automountServiceAccountToken: false
