"""initial schema frozen

Revision ID: 20260812_0001
Revises:
Create Date: 2026-08-12 15:18:56.345384
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260812_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column(
            "platform",
            sa.Enum(
                "ORACLE",
                "POSTGRESQL",
                "SYBASE",
                name="databaseplatform",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("edition", sa.String(length=120), nullable=True),
        sa.Column(
            "environment",
            sa.Enum(
                "PRODUCTION",
                "STAGING",
                "TEST",
                "DEVELOPMENT",
                "DISASTER_RECOVERY",
                name="assetenvironment",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("owner", sa.String(length=160), nullable=False),
        sa.Column("criticality", sa.String(length=16), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "DECOMMISSIONED",
                name="lifecyclestatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("tenant_id", "external_id", name="uq_assets_tenant_external"),
    )
    op.create_index(op.f("ix_assets_created_at"), "assets", ["created_at"], unique=False)
    op.create_index(op.f("ix_assets_tenant_id"), "assets", ["tenant_id"], unique=False)
    op.create_index("ix_assets_tenant_platform", "assets", ["tenant_id", "platform"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=160), nullable=False),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("source_ip", sa.String(length=64), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_occurred_at"), "audit_events", ["occurred_at"], unique=False
    )
    op.create_index(op.f("ix_audit_events_tenant_id"), "audit_events", ["tenant_id"], unique=False)
    op.create_index(
        "ix_audit_tenant_occurred", "audit_events", ["tenant_id", "occurred_at"], unique=False
    )
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("actor_subject", sa.String(length=160), nullable=False),
        sa.Column("authorization_hash", sa.String(length=64), nullable=False),
        sa.Column("method", sa.String(length=12), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("response_content_type", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint(
            "tenant_id",
            "actor_subject",
            "authorization_hash",
            "method",
            "path",
            "idempotency_key",
            name="uq_idempotency_scope",
        ),
    )
    op.create_index("ix_idempotency_expiry", "idempotency_records", ["expires_at"], unique=False)
    op.create_table(
        "masking_policies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("classification", sa.String(length=100), nullable=False),
        sa.Column("strategy", sa.String(length=80), nullable=False),
        sa.Column(
            "target_environment",
            sa.Enum(
                "PRODUCTION",
                "STAGING",
                "TEST",
                "DEVELOPMENT",
                "DISASTER_RECOVERY",
                name="assetenvironment",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("approved_by", sa.String(length=160), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_masking_policies")),
        sa.UniqueConstraint("tenant_id", "name", "version", name="uq_masking_tenant_name_version"),
    )
    op.create_index(
        op.f("ix_masking_policies_created_at"), "masking_policies", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_masking_policies_tenant_id"), "masking_policies", ["tenant_id"], unique=False
    )
    op.create_table(
        "access_reviews",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("reviewer", sa.String(length=160), nullable=False),
        sa.Column("scope", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "IN_REVIEW",
                "APPROVED",
                "REMEDIATION_REQUIRED",
                "CLOSED",
                name="reviewstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decision_summary", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_access_reviews_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_reviews")),
    )
    op.create_index(
        op.f("ix_access_reviews_asset_id"), "access_reviews", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_access_reviews_created_at"), "access_reviews", ["created_at"], unique=False
    )
    op.create_index(
        "ix_access_reviews_tenant_asset", "access_reviews", ["tenant_id", "asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_access_reviews_tenant_id"), "access_reviews", ["tenant_id"], unique=False
    )
    op.create_table(
        "assessments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("control_pack", sa.String(length=120), nullable=False),
        sa.Column("control_pack_version", sa.String(length=40), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                name="assessmentstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("initiated_by", sa.String(length=160), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_assessments_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessments")),
    )
    op.create_index(op.f("ix_assessments_asset_id"), "assessments", ["asset_id"], unique=False)
    op.create_index(op.f("ix_assessments_created_at"), "assessments", ["created_at"], unique=False)
    op.create_index(
        "ix_assessments_tenant_asset", "assessments", ["tenant_id", "asset_id"], unique=False
    )
    op.create_index(op.f("ix_assessments_tenant_id"), "assessments", ["tenant_id"], unique=False)
    op.create_table(
        "connectors",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column(
            "platform",
            sa.Enum(
                "ORACLE",
                "POSTGRESQL",
                "SYBASE",
                name="databaseplatform",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("endpoint_ref", sa.String(length=512), nullable=False),
        sa.Column("secret_ref", sa.String(length=1024), nullable=False),
        sa.Column("collector_id", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_connectors_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connectors")),
        sa.UniqueConstraint("tenant_id", "name", name="uq_connectors_tenant_name"),
    )
    op.create_index(op.f("ix_connectors_asset_id"), "connectors", ["asset_id"], unique=False)
    op.create_index(
        op.f("ix_connectors_collector_id"), "connectors", ["collector_id"], unique=False
    )
    op.create_index(op.f("ix_connectors_created_at"), "connectors", ["created_at"], unique=False)
    op.create_index(op.f("ix_connectors_tenant_id"), "connectors", ["tenant_id"], unique=False)
    op.create_index(
        "ix_connectors_tenant_status", "connectors", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "findings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("assessment_id", sa.String(length=36), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("control_id", sa.String(length=100), nullable=False),
        sa.Column("fingerprint", sa.String(length=128), nullable=False),
        sa.Column(
            "domain",
            sa.Enum(
                "ENCRYPTION",
                "DATA_PROTECTION",
                "ACCESS_SECURITY",
                "DATA_MASKING",
                name="controldomain",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "CRITICAL",
                "HIGH",
                "MEDIUM",
                "LOW",
                "INFO",
                name="findingseverity",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "IN_PROGRESS",
                "RISK_ACCEPTED",
                "RESOLVED",
                "FALSE_POSITIVE",
                name="findingstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("owner", sa.String(length=160), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remediation", sa.Text(), nullable=False),
        sa.Column("risk_context", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
            name=op.f("fk_findings_assessment_id_assessments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_findings_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
        sa.UniqueConstraint(
            "tenant_id",
            "assessment_id",
            "control_id",
            "fingerprint",
            name="uq_findings_assessment_control_fingerprint",
        ),
    )
    op.create_index(op.f("ix_findings_assessment_id"), "findings", ["assessment_id"], unique=False)
    op.create_index(op.f("ix_findings_asset_id"), "findings", ["asset_id"], unique=False)
    op.create_index(op.f("ix_findings_created_at"), "findings", ["created_at"], unique=False)
    op.create_index(op.f("ix_findings_tenant_id"), "findings", ["tenant_id"], unique=False)
    op.create_index(
        "ix_findings_tenant_status_severity",
        "findings",
        ["tenant_id", "status", "severity"],
        unique=False,
    )
    op.create_table(
        "scan_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("connector_id", sa.String(length=36), nullable=False),
        sa.Column("assessment_id", sa.String(length=36), nullable=True),
        sa.Column("job_type", sa.String(length=80), nullable=False),
        sa.Column("deduplication_key", sa.String(length=160), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "LEASED",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "CANCELLED",
                name="workstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("leased_by", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
            name=op.f("fk_scan_jobs_assessment_id_assessments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["connector_id"],
            ["connectors.id"],
            name=op.f("fk_scan_jobs_connector_id_connectors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_jobs")),
        sa.UniqueConstraint("tenant_id", "deduplication_key", name="uq_jobs_tenant_dedup"),
    )
    op.create_index(
        "ix_jobs_lease_queue", "scan_jobs", ["tenant_id", "status", "available_at"], unique=False
    )
    op.create_index(
        op.f("ix_scan_jobs_assessment_id"), "scan_jobs", ["assessment_id"], unique=False
    )
    op.create_index(op.f("ix_scan_jobs_connector_id"), "scan_jobs", ["connector_id"], unique=False)
    op.create_index(op.f("ix_scan_jobs_created_at"), "scan_jobs", ["created_at"], unique=False)
    op.create_index(op.f("ix_scan_jobs_tenant_id"), "scan_jobs", ["tenant_id"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("assessment_id", sa.String(length=36), nullable=False),
        sa.Column("finding_id", sa.String(length=36), nullable=True),
        sa.Column("control_id", sa.String(length=100), nullable=False),
        sa.Column("evidence_type", sa.String(length=64), nullable=False),
        sa.Column("uri", sa.String(length=1024), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("collector_version", sa.String(length=40), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
            name=op.f("fk_evidence_assessment_id_assessments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
            name=op.f("fk_evidence_finding_id_findings"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
    )
    op.create_index(op.f("ix_evidence_assessment_id"), "evidence", ["assessment_id"], unique=False)
    op.create_index(op.f("ix_evidence_created_at"), "evidence", ["created_at"], unique=False)
    op.create_index(op.f("ix_evidence_finding_id"), "evidence", ["finding_id"], unique=False)
    op.create_index(
        "ix_evidence_tenant_assessment", "evidence", ["tenant_id", "assessment_id"], unique=False
    )
    op.create_index(op.f("ix_evidence_tenant_id"), "evidence", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evidence_tenant_id"), table_name="evidence")
    op.drop_index("ix_evidence_tenant_assessment", table_name="evidence")
    op.drop_index(op.f("ix_evidence_finding_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_created_at"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_assessment_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_scan_jobs_tenant_id"), table_name="scan_jobs")
    op.drop_index(op.f("ix_scan_jobs_created_at"), table_name="scan_jobs")
    op.drop_index(op.f("ix_scan_jobs_connector_id"), table_name="scan_jobs")
    op.drop_index(op.f("ix_scan_jobs_assessment_id"), table_name="scan_jobs")
    op.drop_index("ix_jobs_lease_queue", table_name="scan_jobs")
    op.drop_table("scan_jobs")
    op.drop_index("ix_findings_tenant_status_severity", table_name="findings")
    op.drop_index(op.f("ix_findings_tenant_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_created_at"), table_name="findings")
    op.drop_index(op.f("ix_findings_asset_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_assessment_id"), table_name="findings")
    op.drop_table("findings")
    op.drop_index("ix_connectors_tenant_status", table_name="connectors")
    op.drop_index(op.f("ix_connectors_tenant_id"), table_name="connectors")
    op.drop_index(op.f("ix_connectors_created_at"), table_name="connectors")
    op.drop_index(op.f("ix_connectors_collector_id"), table_name="connectors")
    op.drop_index(op.f("ix_connectors_asset_id"), table_name="connectors")
    op.drop_table("connectors")
    op.drop_index(op.f("ix_assessments_tenant_id"), table_name="assessments")
    op.drop_index("ix_assessments_tenant_asset", table_name="assessments")
    op.drop_index(op.f("ix_assessments_created_at"), table_name="assessments")
    op.drop_index(op.f("ix_assessments_asset_id"), table_name="assessments")
    op.drop_table("assessments")
    op.drop_index(op.f("ix_access_reviews_tenant_id"), table_name="access_reviews")
    op.drop_index("ix_access_reviews_tenant_asset", table_name="access_reviews")
    op.drop_index(op.f("ix_access_reviews_created_at"), table_name="access_reviews")
    op.drop_index(op.f("ix_access_reviews_asset_id"), table_name="access_reviews")
    op.drop_table("access_reviews")
    op.drop_index(op.f("ix_masking_policies_tenant_id"), table_name="masking_policies")
    op.drop_index(op.f("ix_masking_policies_created_at"), table_name="masking_policies")
    op.drop_table("masking_policies")
    op.drop_index("ix_idempotency_expiry", table_name="idempotency_records")
    op.drop_table("idempotency_records")
    op.drop_index("ix_audit_tenant_occurred", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_tenant_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_occurred_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("ix_assets_tenant_platform", table_name="assets")
    op.drop_index(op.f("ix_assets_tenant_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_created_at"), table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
